### ISSUE TITLE
Finding the correct correct scripts to Install

### ISSUE THREAD

**Issue by naveen521kk** [msys2/msys2-texlive#10]
I gave up hardcoding scripts and it became a bit hard. So, I decided to create a file that will contain a list of all the scripts that needs to be installed for a package.

https://github.com/msys2/msys2-texlive/blob/da3d1670f1322310ba4b516d4332282b480f5beb/texlive/file_creator.py#L418-L483

After that, I found there were some conflicts with scripts installed and some being like creating things like `inkscape.exe`, `gs.exe` which conflicted with other mingw-packages that existed. 

@norbusan Can you help me in finding this? Currently what I do is search using this regex `^( *)texmf-dist\/scripts\/(?P<script_name>[\/\w\-]*)\.(?P<script_ext>[\/\w\-]*)` in texlive.tlpdb. Is this correct? What is done by tlmgr?

**Comment by norbusan** [comment]
Oh well, that is indeed a mess ;-) Too long to explain the history that led to this, but well ...

tlmgr doesn't do anything in this respect, since the $pkg.$arch containers (tar.xz) already contain the links from the binary directories to the correct texmf-dist/scripts/...

So I am not really sure what your problem is.

**Comment by naveen521kk** [comment]
> tlmgr doesn't do anything in this respect, since the $pkg.$arch containers (tar.xz) already contain the links from the binary directories to the correct texmf-dist/scripts/...

Ah, I wasn't expecting that. So, I should look at what they tlmgr do.

> So I am not really sure what your problem is.

What I am trying to do is to find which are all the scripts that need a launcher, for a specific set of packages. For example, Arch Linux has something like this 

https://github.com/archlinux/svntogit-packages/blob/17b510cff66b761b0027fff368efcb54946b5f4c/trunk/PKGBUILD#L172-L308

and they create symlinks for the scripts there. I need to do the same thing, but unsure of how to find those scripts in a package.

**Comment by norbusan** [comment]
That should do it https://github.com/TeX-Live/texlive-source/blob/trunk/texk/texlive/linked_scripts/scripts.lst

**Comment by naveen521kk** [comment]
I have seen that previously, but it for all the packages on the whole right? Is it possible for getting it specifically for a package(or a collection)? (if it isn't possible, or is very hard to automate I would simply put these in a single mingw-package).

**Comment by norbusan** [comment]
For each package that contains files in texmf-dist/scripts check whether it is in this list. That should be trivial to automatize. This is what I do in Debian, loop over the files of a package and check against the linked scripts entries.

**Comment by naveen521kk** [comment]
Ok, got it. Should be simple enough.
