### ISSUE TITLE
About Biber

### ISSUE THREAD

**Issue by angelog0** [msys2/msys2-texlive#11]
It seem you don't have `biber`. Right?

**Comment by naveen521kk** [comment]
No. It should be created as a separate package, like Archlinux's https://github.com/archlinux/svntogit-community/blob/packages/biber/trunk/PKGBUILD.

**Comment by angelog0** [comment]
All TeXLive distributions I know do have Biber. I don't understand why one should file a PR for it...

**Comment by naveen521kk** [comment]
> All TeXLive distributions I know do have Biber.

I know, I previously said, all on texlive in MSYS2 is still a WIP.

> I don't understand why one should file a PR for it...

If you need it urgently you should go first. Or else wait for me (It would at least take some months for me to add them).

**Comment by naveen521kk** [comment]
Also, this issue shouldn't be here, this should in the [MINGW-packages](https://github.com/msys2/MINGW-packages) repo.
