### ISSUE TITLE
Verify the downloaded sources

### ISSUE THREAD

**Issue by naveen521kk** [msys2/msys2-texlive#2]
Looks like there are 
- sha512 sums, in `texlive.tlpdb` 
- are signed with gpg key https://tug.org/texlive/files/texlive.asc. 

We should verify the files we download at least using one of the methods.

**Comment by norbusan** [comment]
This is not *one* of the methods, but a chain:

* the gpg signature verifies that the texlive.tlpdb is correct, and thus the therein saved sha512 files are correct
* then you can use the sha512 to verify that the actual packages are what they should be

I wrote it, let me know if you need more explanations.

**Comment by naveen521kk** [comment]
So, get `texlive.tlpdb`, `texlive.tlpdb.sha512` and `texlive.tlpdb.sha512.asc`, verify that `texlive.tlpdb.sha512` is correct, then use the checksum from it to verify that `texlive.tlpdb` is correct. Then while downloading archive just verify that sha512 sums match with the one from `texlive.tlpdb`.

Is this right?

**Comment by norbusan** [comment]
Perfect!
