### ISSUE TITLE
xdvipdfmx error

### ISSUE THREAD

**Issue by Chief-byte** [msys2/msys2-texlive#20]
xdvipdfmx doesnt work after updated `mingw-w64-ucrt-x86_64-texlive-bin` to  2023.20230523-2.

It just shows xdvipdfmx:fatal: Unrecognized paper format: a4 xelatex.exe: fwrite: Broken pipe when I compiling any file.

**Comment by naveen521kk** [comment]
I just tried compiling a test file and it works. I'll try what's happening in a clean install and check. Also, see https://github.com/msys2/MINGW-packages/issues/17771#issuecomment-1636701589

**Comment by naveen521kk** [comment]
The issue should be fixed, see https://github.com/msys2/MINGW-packages/issues/17771.
