### ISSUE TITLE
File Conflicts in Packages

### ISSUE THREAD

**Issue by naveen521kk** [msys2/msys2-texlive#6]
I have opened https://github.com/msys2/MINGW-packages/pull/8496 for adding other packages as an example I added `texlive-latexextra` package. When Pacman when checking for file conflicts, failed. I could find these are the file conflicts.
See 
[conflicts.txt](https://github.com/msys2/msys2-texlive/files/6392118/conflicts.txt)
for a list of conflict. This should be handled here rather than cleaning them in manually in that PKGBUILD.

@norbusan can you help me with what I can do here? Mixing between `scheme-medium` and `collections` seems to be wrong to me, but not sure.

**Comment by norbusan** [comment]
Of course I can ;-)

Schemes are not guaranteed to be non-overlapping, while we guarantee (with some bugs of course) that collections form a partition of all packages, that is, that no package and thus no file is contained in two collections.

OTOH, lots of files are contained in different schemes.

That means, that if you don't your packaging, I strongly suggest to do it along collection boundaries, and not solely based on schemes.

Does that help out am I too unclear?

**Comment by norbusan** [comment]
Well, I am not the one to ask about whether the Debian way is the correct one, right? ;-)

But yes, splitting at collection boundaries is a good idea. In one of my presentation I said there are three basic ways: (1) all in one (2) split at collections level, (3) split at single package level

Debian uses (2), Fedora and SUSE as far as I see use (3), nobody uses (1) AFAIS. Other ways only are a recipe for problems.

Concerning the doc splitting in Debian - this was only to satisfy demands - I don't like it, but bowed to requests.

**Comment by naveen521kk** [comment]
Looks like splitting at the collection level is a good idea (splitting at the package level is a lot of work), maybe I spend some time tomorrow to get things working.

**Comment by naveen521kk** [comment]
I have come with something like
```py
PACKAGE_COLLECTION = {
    "texlive-core": [
        "collection-basic",
        "collection-xetex",
        "collection-context",
    ],
    "texlive-bibtex-extra": "collection-bibtexextra",
    "texlive-extra-utils": "collection-binextra",
    "texlive-fonts-extra": "collection-fontsextra",
    "texlive-fonts-recommended": "collection-fontsrecommended",
    "texlive-font-utils": "collection-fontutils",
    "texlive-formats-extra": "collection-formatsextra",
    "texlive-games": "collection-games",
    "texlive-humanities": "collection-humanities",
    "texlive-lang-arabic": "collection-langarabic",
    "texlive-lang-chinese": "collection-langchinese",
    "texlive-lang-cjk": "collection-langcjk",
    "texlive-lang-cyrillic": "collection-langcyrillic",
    "texlive-lang-czechslovak": "collection-langczechslovak",
    "texlive-lang-english": "collection-langenglish",
    "texlive-lang-european": "collection-langeuropean",
    "texlive-lang-french": "collection-langfrench",
    "texlive-lang-german": "collection-langgerman",
    "texlive-lang-greek": "collection-langgreek",
    "texlive-lang-italian": "collection-langitalian",
    "texlive-lang-japanese": "collection-langjapanese",
    "texlive-lang-korean": "collection-langkorean",
    "texlive-lang-other": "collection-langother",
    "texlive-lang-polish": "collection-langpolish",
    "texlive-lang-portuguese": "collection-langportuguese",
    "texlive-lang-spanish": "collection-langspanish",
    "texlive-latex-base": "collection-latex",
    "texlive-latex-extra": "collection-latexextra",
    "texlive-latex-recommended": "collection-latexrecommended",
    "texlive-luatex": "collection-luatex",
    "texlive-metapost": "collection-metapost",
    "texlive-music": "collection-music",
    "texlive-pictures": "collection-pictures",
    "texlive-plain-generic": "collection-plaingeneric",
    "texlive-pstricks": "collection-pstricks",
    "texlive-publishers": "collection-publishers",
    "texlive-science": "collection-mathscience",
}
```
where the left side is package name right is collection name. Does this look good?

**Comment by naveen521kk** [comment]
Ah! Looks like some collections depend on other collections and parsing it recursively as it is done now, is problematic and introduces conflicts again. 
https://github.com/msys2/msys2-texlive/blob/0c2ce01c667d19509aa572e6adc8e582673fc5fe/texlive/main.py#L122-L157
I am going to push a fix to make it not happen and, that means when creating the packages I should look for the correct dependencies.

**Comment by norbusan** [comment]
Ah well yes, collection->collection dependencies should be transformed into package manager dependencies, if possible.
And the above collection => package name mapping looks fine, there you are completely free.

**Comment by naveen521kk** [comment]
> Ah well yes, collection->collection dependencies should be transformed into package manager dependencies, if possible.

Yeah, that's what I though of doing.

>  And the above collection => package name mapping looks fine, there you are completely free.

I think I shouldn't do any recursion, here in parsing dependencies even for packages, because it also creates conflicts again. But I'm worried that this may miss any packages, can you help me? By recursion, I mean parsing dependency of a dependency.

**Comment by norbusan** [comment]
No you won't miss any package, every package is contained in exactly one collection (as I said, they form a partition ;-)
